# Generated by Django 4.2.11 on 2026-05-17 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0004_solicitudservicio_estatus_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
