# Generated by Django 4.2.11 on 2026-05-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_solicitudservicio_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltecnico',
            name='foto_trabajo',
            field=models.ImageField(blank=True, null=True, upload_to='trabajos_tecnicos/'),
        ),
    ]
