# Generated by Django 4.2.11 on 2026-05-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='perfiltecnico',
            name='especialidades',
            field=models.ManyToManyField(blank=True, to='servicios.especialidad'),
        ),
    ]
