# Generated by Django 4.2.11 on 2026-05-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_especialidad_perfiltecnico_especialidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiltecnico',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='perfiltecnico',
            name='experiencia',
        ),
        migrations.AddField(
            model_name='perfiltecnico',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfiltecnico',
            name='presentacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfiltecnico',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
