# Generated by Django 4.2.11 on 2026-05-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_solicitudservicio_estado_trabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltecnico',
            name='esta_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
